openapi: 3.0.0
info:
  title: HAR API
  description: Human Action Recognition API via smartphone accelerometer data.
  version: 1.0.0
servers:
  - url: https://dev.turaapp.com/
paths:
  /har/:
    post:
      summary: Analyze Sensor Stream
      description: Real-time inference using RF (Primary) and 1D-CNN (Secondary).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sampling_rate: {type: integer, example: 50}
                timestamp: {type: integer, example: 1675680000}
                samples:
                  type: array
                  items: {type: array, items: {type: number}}
                  example: [[-0.1, 9.8, 0.5], [0.0, 9.7, 0.6]]
      responses:
        '200':
          description: Successful Inference
          content:
            application/json:
              schema:
                type: object
                properties:
                  label: {type: string}
                  confidence: {type: number}
                  model: {type: string}
                  timestamp: {type: number}
                  dl_result: {type: object}
        '400': {description: Validation Error}
  /har/latest/:
    get:
      summary: Retrieve Live Stream State
      description: Returns the most recent classification and a short temporal history.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  latest: {type: object}
                  history: {type: array, items: {type: object}}
